x-backend-variables: &backend-variables
  ENVIRONMENT: ${ENVIRONMENT:-local}

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${ENVIRONMENT}-donezo_web"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./pyproject.toml:/app/pyproject.toml
      - ./uv.lock:/app/uv.lock
    environment:
      <<: *backend-variables
    restart: on-failure
    networks:
      local:

networks:
  local:
    name: "${ENVIRONMENT}_local"
    driver: bridge
